import { CalendarDays, CheckCircle2, Clock3, Laptop, LogIn, LogOut, MapPin } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { AttendanceRecord, getMyAttendance, MyAttendanceResult, remoteClock } from '../lib/api';
import { cn } from '../lib/utils';

const currentMonth = new Date().toISOString().slice(0, 7);
const statusColor:Record<string,string>={remote:'bg-indigo-50 text-indigo-700',present:'bg-emerald-50 text-emerald-700',late:'bg-amber-50 text-amber-700',absent:'bg-rose-50 text-rose-700',on_leave:'bg-violet-50 text-violet-700'};
const time=(value:string|null)=>value?new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'--';
const label=(value:string)=>value.split('_').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ');
const monthRange=(month:string)=>{const[y,m]=month.split('-').map(Number);return{start_date:`${month}-01`,end_date:new Date(y,m,0).toISOString().slice(0,10)}};

export default function EmployeeAttendancePage(){
 const[month,setMonth]=useState(currentMonth);const[data,setData]=useState<MyAttendanceResult|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=useCallback(()=>{setLoading(true);setError('');getMyAttendance(monthRange(month)).then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load your attendance.')).finally(()=>setLoading(false));},[month]);
 useEffect(()=>{load()},[load]);
 const clock=async(action:'in'|'out')=>{setWorking(true);setError('');setMessage('');try{await remoteClock(action);setMessage(action==='in'?'Remote clock-in recorded.':'Remote clock-out recorded.');load()}catch(e){setError(e instanceof Error?e.message:'Unable to update attendance.')}finally{setWorking(false)}};
 const today=data?.today;const canIn=!today;const canOut=Boolean(today?.check_in&&!today?.check_out);
 return <div className="mx-auto max-w-6xl space-y-7">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-bold">My Attendance</h2><p className="mt-2 text-slate-500">View your records and record remote working time.</p></div><label className="text-xs font-bold uppercase text-slate-400">History month<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-2 block h-11 rounded-xl border bg-white px-4 text-sm font-semibold text-slate-700"/></label></div>
  <section className="grid gap-5 lg:grid-cols-[1.2fr_2fr]">
   <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Laptop className="h-6 w-6"/></span><div><h3 className="font-bold">Remote Work Clock</h3><p className="text-sm text-slate-500">Today, {new Date().toLocaleDateString()}</p></div></div><div className="mt-6 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span className="text-slate-500">Clock in</span><b>{time(today?.check_in??null)}</b></div><div className="mt-3 flex justify-between text-sm"><span className="text-slate-500">Clock out</span><b>{time(today?.check_out??null)}</b></div><div className="mt-3 flex justify-between text-sm"><span className="text-slate-500">Location</span><b>{today?.location??'Remote'}</b></div></div><div className="mt-5 grid grid-cols-2 gap-3"><button disabled={!canIn||working} onClick={()=>clock('in')} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300"><LogIn className="h-4 w-4"/>Clock In</button><button disabled={!canOut||working} onClick={()=>clock('out')} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-indigo-200 bg-white font-bold text-indigo-600 disabled:cursor-not-allowed disabled:border-slate-200 disabled:text-slate-300"><LogOut className="h-4 w-4"/>Clock Out</button></div>{today?.check_out&&<p className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-600"><CheckCircle2 className="h-4 w-4"/>Today’s remote shift is complete.</p>}</article>
   <div className="grid gap-4 sm:grid-cols-2"><Stat label="Remote days" value={data?.stats.remote??0} icon={MapPin} color="bg-indigo-50 text-indigo-600"/><Stat label="Present days" value={data?.stats.present??0} icon={CheckCircle2} color="bg-emerald-50 text-emerald-600"/><Stat label="Late days" value={data?.stats.late??0} icon={Clock3} color="bg-amber-50 text-amber-600"/><Stat label="Leave days" value={data?.stats.on_leave??0} icon={CalendarDays} color="bg-violet-50 text-violet-600"/></div>
  </section>
  {error&&<p className="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}{message&&<p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="border-b p-6"><h3 className="text-xl font-bold">My Attendance History</h3><p className="mt-1 text-sm text-slate-500">Only records belonging to {data?.employee.name??'your account'} are shown.</p></header>{loading?<p className="p-12 text-center text-slate-500">Loading your attendance...</p>:<History records={data?.items??[]}/>}</section>
 </div>
}
function Stat({label:caption,value,icon:Icon,color}:{label:string;value:number;icon:typeof Clock3;color:string}){return <article className="flex items-center justify-between rounded-2xl border bg-white p-6"><div><p className="text-xs font-bold uppercase text-slate-400">{caption}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><span className={cn('flex h-12 w-12 items-center justify-center rounded-xl',color)}><Icon className="h-6 w-6"/></span></article>}
function History({records}:{records:AttendanceRecord[]}){return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Date','Clock In','Clock Out','Work Time','Location','Status'].map(x=><th key={x} className="px-6 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{records.map(record=><tr key={record.id}><td className="px-6 py-4 font-semibold">{record.date}</td><td className="px-6 py-4">{time(record.check_in)}</td><td className="px-6 py-4">{time(record.check_out)}</td><td className="px-6 py-4">{Math.floor(record.work_minutes/60)}h {record.work_minutes%60}m</td><td className="px-6 py-4">{record.location??'--'}</td><td className="px-6 py-4"><span className={cn('rounded-full px-3 py-1 text-xs font-bold',statusColor[record.status]??'bg-slate-100 text-slate-600')}>{label(record.status)}</span></td></tr>)}{!records.length&&<tr><td colSpan={6} className="p-12 text-center text-slate-500">No attendance records for this month.</td></tr>}</tbody></table></div>}
