import { ArrowLeft, MoreVertical, Save, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { getPayrollSetting, getSalaryList, savePayrollSetting } from '../lib/api';

type Mode = 'bank' | 'payslip' | 'salary-list';
type Salary = { id:number;name:string;employee_code:string;department:string|null;base_salary:number;net_salary:number|null;last_paid:string|null };

export default function PayrollUtilityPage({ mode, onNavigate }: { mode:Mode; onNavigate:(path:string)=>void }) {
  const [search, setSearch] = useState('');
  const [salaries, setSalaries] = useState<Salary[]>([]);
  const [setting, setSetting] = useState<Record<string, unknown>>({ company_name:'Siegecode HRM', address:'', bank_name:'', account_number:'', swift_code:'', show_logo:true, show_leave:true, show_attendance:true });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (mode === 'salary-list') getSalaryList(search).then(setSalaries);
    else getPayrollSetting(mode).then((value) => setSetting((current) => ({ ...current, ...value })));
  }, [mode, search]);

  const update = (key:string, value:unknown) => setSetting((current) => ({ ...current, [key]:value }));
  const save = async () => { if (mode === 'salary-list') return; setSaving(true); await savePayrollSetting(mode, setting); setSaving(false); };

  if (mode === 'salary-list') {
    return <div className="mx-auto max-w-7xl space-y-6"><Back onNavigate={onNavigate}/><h2 className="text-3xl font-bold">Employee Salary List</h2><label className="flex h-14 items-center gap-3 rounded-3xl bg-white px-5"><Search className="h-5 w-5 text-slate-400"/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search employees, ID or department..." className="h-full flex-1 bg-transparent outline-none"/></label><div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Employee','Department','Base Salary','Net Salary','Last Paid','Action'].map((label)=><th key={label} className="px-6 py-4">{label}</th>)}</tr></thead><tbody>{salaries.map((item)=><tr key={item.id} className="border-t"><td className="px-6 py-4 font-bold">{item.name}<p className="text-xs text-slate-400">{item.employee_code}</p></td><td className="px-6 py-4">{item.department??'—'}</td><td className="px-6 py-4 font-bold">${item.base_salary.toLocaleString()}</td><td className="px-6 py-4 font-bold text-indigo-600">{item.net_salary===null?'Not processed':`$${item.net_salary.toLocaleString()}`}</td><td className="px-6 py-4">{item.last_paid??'—'}</td><td className="px-6 py-4"><MoreVertical className="h-5 w-5 text-slate-400"/></td></tr>)}{!salaries.length&&<tr><td colSpan={6} className="p-12 text-center text-slate-500">No employees found.</td></tr>}</tbody></table></div></div>;
  }

  return <div className="mx-auto max-w-6xl space-y-6"><Back onNavigate={onNavigate}/><section className="rounded-2xl border bg-white p-8"><div className="flex justify-between"><div><h2 className="text-3xl font-bold">{mode==='bank'?'Company Bank Details':'Payslip Customization'}</h2><p className="mt-2 text-slate-500">{mode==='bank'?'Manage the primary account for salary disbursements.':'Design how employees see their salary breakdown.'}</p></div><button onClick={save} className="flex h-11 items-center gap-2 rounded-xl bg-indigo-600 px-6 font-bold text-white"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Changes'}</button></div>{mode==='bank'?<BankForm setting={setting} update={update}/>:<PayslipForm setting={setting} update={update}/>}</section></div>;
}

function BankForm({setting,update}:{setting:Record<string,unknown>;update:(key:string,value:unknown)=>void}) { return <div className="mt-8 grid gap-5 md:grid-cols-2"><Input label="Bank Name" value={setting.bank_name} onChange={(value)=>update('bank_name',value)}/><Input label="Account Number" value={setting.account_number} onChange={(value)=>update('account_number',value)}/><Input label="SWIFT / BIC" value={setting.swift_code} onChange={(value)=>update('swift_code',value)}/><div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-700">Payment gateway is not connected. Saving bank details does not initiate transfers.</div></div>; }
function PayslipForm({setting,update}:{setting:Record<string,unknown>;update:(key:string,value:unknown)=>void}) { return <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_1.5fr]"><div className="space-y-4"><Toggle label="Show Company Logo" value={Boolean(setting.show_logo)} onChange={(value)=>update('show_logo',value)}/><Toggle label="Display Leave Balance" value={Boolean(setting.show_leave)} onChange={(value)=>update('show_leave',value)}/><Toggle label="Show Attendance Summary" value={Boolean(setting.show_attendance)} onChange={(value)=>update('show_attendance',value)}/><Input label="Company Name" value={setting.company_name} onChange={(value)=>update('company_name',value)}/><Input label="Address" value={setting.address} onChange={(value)=>update('address',value)}/></div><div className="rounded-2xl bg-slate-100 p-8"><div className="min-h-[520px] bg-white p-8 shadow-lg"><h3 className="text-2xl font-bold text-emerald-600">PAYSLIP</h3><h4 className="mt-8 text-xl font-bold">{String(setting.company_name||'Company Name')}</h4><p className="text-sm text-slate-500">{String(setting.address||'Company address')}</p><div className="my-8 border-t"/><div className="grid grid-cols-2 gap-8"><div><p className="text-xs font-bold uppercase text-slate-400">Employee Details</p><p className="mt-3 font-bold">Employee Name</p></div><div className="text-right"><p className="text-xs font-bold uppercase text-slate-400">Payment Info</p><p className="mt-3">Bank: Configured Account</p></div></div><div className="mt-12 grid grid-cols-2 gap-8"><div><h5 className="font-bold text-emerald-600">Earnings</h5><p className="mt-4">Basic Salary</p></div><div><h5 className="font-bold text-rose-600">Deductions</h5><p className="mt-4">Income Tax</p></div></div></div></div></div>; }
function Back({onNavigate}:{onNavigate:(path:string)=>void}) { return <button onClick={()=>onNavigate('payroll/settings')} className="flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>Payroll Setting</button>; }
function Input({label,value,onChange}:{label:string;value:unknown;onChange:(value:string)=>void}) { return <label className="text-sm font-bold">{label}<input value={String(value??'')} onChange={(event)=>onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-slate-50 px-4"/></label>; }
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}) { return <label className="flex items-center justify-between rounded-xl bg-slate-50 p-4 font-bold"><span>{label}</span><input type="checkbox" checked={value} onChange={(event)=>onChange(event.target.checked)}/></label>; }
