import { ArrowLeft, MoreVertical, Save, Search } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { createPayrollConfig, getPayrollConfig } from '../lib/api';
type Item=Record<string,unknown>&{id:number};
const names:Record<string,string>={components:'Salary Components',cycles:'Payroll Cycle',taxes:'Tax Rules & Slabs',policies:'Payroll Policy'};
const fieldClass='mt-2 h-11 w-full rounded-xl border bg-slate-50 px-4 font-normal';
export default function PayrollConfigPage({kind,onNavigate}:{kind:string;onNavigate:(path:string)=>void}){
 const[items,setItems]=useState<Item[]>([]);const[form,setForm]=useState<Record<string,unknown>>({component_type:'earning',calculation_type:'fixed',frequency:'monthly',is_default:false,category:'deduction',count_type:'daily',policy_type:'regular',value_mode:'amount'});const[search,setSearch]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);
 const load=()=>getPayrollConfig<Item>(kind).then(setItems).catch((requestError)=>setError(requestError instanceof Error?requestError.message:'Unable to load configuration.'));
 useEffect(()=>{void load();},[kind]);
 const update=(key:string,value:unknown)=>setForm((current)=>({...current,[key]:value}));
 const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await createPayrollConfig(kind,form);await load();}catch(requestError){setError(requestError instanceof Error?requestError.message:'Unable to save.');}finally{setSaving(false);}};
 const visible=items.filter((item)=>JSON.stringify(item).toLowerCase().includes(search.toLowerCase()));
 return <div className="mx-auto max-w-7xl space-y-6"><button onClick={()=>onNavigate('payroll/settings')}className="flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>Payroll Setting</button><section className="rounded-2xl border bg-white p-8"><h2 className="text-3xl font-bold">{names[kind]}</h2><p className="mt-2 text-slate-500">Configure payroll calculation and processing rules.</p><form onSubmit={submit}className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Fields kind={kind}form={form}update={update}/>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700 md:col-span-4">{error}</p>}<button disabled={saving}className="flex h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 font-bold text-white"><Save className="h-4 w-4"/>{saving?'Saving...':'Create'}</button></form></section><label className="flex h-14 items-center gap-3 rounded-3xl bg-white px-5"><Search className="h-5 w-5 text-slate-400"/><input value={search}onChange={(event)=>setSearch(event.target.value)}className="h-full flex-1 bg-transparent outline-none"/></label><section className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Name / Range','Type','Value / Details','Status','Action'].map((label)=><th key={label}className="px-6 py-4">{label}</th>)}</tr></thead><tbody>{visible.map((item)=><tr key={item.id}className="border-t"><td className="px-6 py-4 font-bold">{String(item.name??`${item.min_income} - ${item.max_income??'No limit'}`)}</td><td className="px-6 py-4 capitalize">{String(item.component_type??item.frequency??item.category??'Tax')}</td><td className="px-6 py-4">{detail(kind,item)}</td><td className="px-6 py-4 text-emerald-600">Active</td><td className="px-6 py-4"><MoreVertical className="h-5 w-5 text-slate-400"/></td></tr>)}{!visible.length&&<tr><td colSpan={5}className="p-12 text-center text-slate-500">No configuration records found.</td></tr>}</tbody></table></section></div>;
}
function Fields({kind,form,update}:{kind:string;form:Record<string,unknown>;update:(key:string,value:unknown)=>void}){if(kind==='components')return <><Field label="Component Name"value={form.name}onChange={(v)=>update('name',v)}/><Select label="Type"value={form.component_type}onChange={(v)=>update('component_type',v)}options={['earning','deduction','bonus']}/><Select label="Calculation Type"value={form.calculation_type}onChange={(v)=>update('calculation_type',v)}options={['fixed','percentage','variable']}/><Field label="Value"value={form.value??0}onChange={(v)=>update('value',v)}type="number"/></>;if(kind==='cycles')return <><Field label="Cycle Name"value={form.name}onChange={(v)=>update('name',v)}/><Select label="Frequency"value={form.frequency}onChange={(v)=>update('frequency',v)}options={['monthly','bi-weekly','weekly']}/><Field label="Pay Day"value={form.pay_day??1}onChange={(v)=>update('pay_day',v)}type="number"/><label className="mt-8"><input type="checkbox"checked={Boolean(form.is_default)}onChange={(e)=>update('is_default',e.target.checked)}/> Set as Default</label></>;if(kind==='taxes')return <><Field label="Minimum Income"value={form.min_income??0}onChange={(v)=>update('min_income',v)}type="number"/><Field label="Maximum Income (optional)"value={form.max_income}onChange={(v)=>update('max_income',v)}type="number"/><Field label="Tax Rate (%)"value={form.rate??0}onChange={(v)=>update('rate',v)}type="number"/><Field label="Description"value={form.description}onChange={(v)=>update('description',v)}/></>;return <><Field label="Policy Name"value={form.name}onChange={(v)=>update('name',v)}/><Select label="Category"value={form.category}onChange={(v)=>update('category',v)}options={['deduction','overtime','earning']}/><Field label="Considerable Value"value={form.considerable_value??0}onChange={(v)=>update('considerable_value',v)}type="number"/><Field label="Adjusted Value"value={form.adjusted_value??0}onChange={(v)=>update('adjusted_value',v)}type="number"/></>}
function Field({label,value,onChange,type='text'}:{label:string;value:unknown;onChange:(value:string)=>void;type?:string}){return <label className="text-sm font-bold">{label}<input required={!label.includes('optional')}type={type}value={String(value??'')}onChange={(e)=>onChange(e.target.value)}className={fieldClass}/></label>}
function Select({label,value,onChange,options}:{label:string;value:unknown;onChange:(value:string)=>void;options:string[]}){return <label className="text-sm font-bold">{label}<select value={String(value??'')}onChange={(e)=>onChange(e.target.value)}className={fieldClass}>{options.map((option)=><option key={option}value={option}>{option}</option>)}</select></label>}
function detail(kind:string,item:Item){if(kind==='components')return`${item.calculation_type}: ${item.value}`;if(kind==='cycles')return`Pay day ${item.pay_day}${item.is_default?' · Default':''}`;if(kind==='taxes')return`${item.rate}% · ${item.description??''}`;return`${item.considerable_value} → ${item.adjusted_value}`}
