import { ArrowLeft, Briefcase, CalendarDays, CheckCircle2, Clock3, ShieldCheck, UserRound, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { getProfileOverview, ProfileOverview } from '../lib/api';

function tenure(from:string|null){if(!from)return 'Not available';const start=new Date(`${from}T00:00:00`);const now=new Date();let months=(now.getFullYear()-start.getFullYear())*12+now.getMonth()-start.getMonth();if(now.getDate()<start.getDate())months--;const years=Math.max(Math.floor(months/12),0);const remainder=Math.max(months%12,0);return `${years} year${years===1?'':'s'}, ${remainder} month${remainder===1?'':'s'}`;}
function label(value:string|null|undefined){return value?value.replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase()):'Not assigned';}

export default function ProfileStatusPage({onNavigate}:{onNavigate:(path:string)=>void}){
 const[data,setData]=useState<ProfileOverview|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{getProfileOverview().then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load status.')).finally(()=>setLoading(false));},[]);
 const employee=data?.employee;const tenureValue=useMemo(()=>tenure(employee?.hire_date??null),[employee?.hire_date]);
 if(loading)return <div className="p-20 text-center text-slate-500">Loading status...</div>;
 if(error||!data)return <div className="rounded-2xl bg-red-50 p-8 text-center text-red-700">{error||'Profile was not found.'}</div>;
 const cards=employee?[["Employment Status",label(employee.status),CheckCircle2,'text-emerald-600 bg-emerald-50'],["Employment Type",label(employee.employment_type),Briefcase,'text-indigo-600 bg-indigo-50'],["Tenure",tenureValue,Clock3,'text-blue-600 bg-blue-50'],["Current Shift",label(employee.shift),CalendarDays,'text-amber-600 bg-amber-50']] as const:[["Account Status",data.account.is_active?'Active':'Inactive',ShieldCheck,'text-emerald-600 bg-emerald-50'],["Access Role",data.account.role??'No role',Users,'text-indigo-600 bg-indigo-50'],["Account Age",tenure(data.account.created_at.slice(0,10)),Clock3,'text-blue-600 bg-blue-50'],["Employee Link","Not linked",UserRound,'text-amber-600 bg-amber-50']] as const;
 return <div className="mx-auto max-w-6xl space-y-7"><button onClick={()=>onNavigate('profile')} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>Employee Profile</button><div><h2 className="text-3xl font-bold">Status</h2><p className="mt-2 text-slate-500">Current account and employment standing.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,Icon,color])=><article key={title} className="flex items-center justify-between rounded-2xl border bg-white p-6 shadow-sm"><div><p className="text-xs font-bold uppercase text-slate-400">{title}</p><p className="mt-2 text-lg font-bold">{value}</p></div><span className={`flex h-12 w-12 items-center justify-center rounded-xl ${color}`}><Icon className="h-6 w-6"/></span></article>)}</div><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="border-b p-6"><h3 className="text-xl font-bold">{employee?'Employment Details':'Account Details'}</h3></header><dl className="grid gap-x-10 gap-y-6 p-7 md:grid-cols-2">{(employee?[["Employee ID",employee.employee_code],["Department",employee.department],["Position",employee.position],["Reporting Manager",employee.manager],["Hire Date",employee.hire_date],["Probation End Date",employee.probation_end_date],["Work Email",employee.email],["Current Shift",employee.shift]]:[["User ID",String(data.account.id)],["Email",data.account.email],["Role",data.account.role],["Created",data.account.created_at.slice(0,10)],["Last Login",data.account.last_login_at?.slice(0,10)??'Not recorded']]).map(([term,value])=><div key={term}><dt className="text-xs font-bold uppercase text-slate-400">{term}</dt><dd className="mt-1 font-semibold text-slate-700">{value||'Not provided'}</dd></div>)}</dl>{!employee&&<div className="border-t bg-amber-50 p-5 text-sm text-amber-700"><b>No employee record is linked to this account.</b> Employment, attendance, leave, salary, and shift details will appear after HR links an employee record.</div>}</section></div>;
}
