import { ArrowLeft, Briefcase, CreditCard, FileText, GraduationCap, Phone, Star, UserRound, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { getProfileOverview, ProfileOverview } from '../lib/api';

const titles:Record<string,string>={information:'Employee Information',bank:'Bank Information',family:'Family & Emergency Contact',education:'Education',employment:'Employment',contact:'Contact Information',supervisor:'Supervisor',documents:'Documents & Passport',payroll:'Payroll & Payslips',performance:'Performance & Reviews'};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
const mask=(value:string|null)=>value?`**** **** ${value.slice(-4)}`:'Not provided';
function Details({items}:{items:Array<[string,string|number|null|undefined]>}){return <dl className="grid gap-x-10 gap-y-6 p-7 md:grid-cols-2">{items.map(([term,value])=><div key={term}><dt className="text-xs font-bold uppercase text-slate-400">{term}</dt><dd className="mt-1 font-semibold text-slate-700">{value??'Not provided'}</dd></div>)}</dl>}
function Empty({message}:{message:string}){return <div className="rounded-2xl border border-dashed bg-white p-14 text-center text-slate-500"><FileText className="mx-auto mb-4 h-9 w-9 text-slate-400"/><b className="text-slate-700">{message}</b></div>}

export default function ProfileDetailPage({section,onNavigate}:{section:string;onNavigate:(path:string)=>void}){
 const[data,setData]=useState<ProfileOverview|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{getProfileOverview().then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load profile details.')).finally(()=>setLoading(false));},[]);
 if(loading)return <div className="p-20 text-center text-slate-500">Loading {titles[section]??'profile'}...</div>;
 if(error||!data)return <div className="rounded-2xl bg-red-50 p-8 text-red-700">{error||'Profile not found.'}</div>;
 const e=data.employee;const title=titles[section]??'Profile Details';
 const accountOnly=<Empty message="No employee record is linked to this account. Ask HR to link an employee before using this section."/>;
 let content:React.ReactNode=accountOnly;
 if(section==='information')content=<section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">{e?'Employee Information':'Account Information'}</h3><Details items={e?[["Full Name",e.name],["Employee ID",e.employee_code],["Work Email",e.email],["Department",e.department],["Position",e.position],["Employment Status",e.status],["Employment Type",e.employment_type],["Hire Date",e.hire_date]]:[["Full Name",data.account.name],["User ID",data.account.id],["Email",data.account.email],["Role",data.account.role],["Account Status",data.account.is_active?'Active':'Inactive'],["Created",data.account.created_at.slice(0,10)]]}/></section>;
 else if(e&&section==='bank')content=<section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Bank Account Details</h3><Details items={[["Bank",e.bank_name],["Account Holder",e.bank_account_name],["Account Number",mask(e.bank_account_number)]]}/></section>;
 else if(e&&section==='family')content=<section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Emergency Contact</h3><Details items={[["Contact Name",e.emergency_contact_name],["Phone Number",e.emergency_contact_phone]]}/><p className="border-t bg-slate-50 p-5 text-sm text-slate-500">Additional family-member records are not configured in the current database.</p></section>;
 else if(e&&section==='education')content=<Empty message="No education records are available for this employee."/>;
 else if(e&&section==='employment')content=<section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Current Employment</h3><Details items={[["Department",e.department],["Position",e.position],["Employment Type",e.employment_type],["Status",e.status],["Hire Date",e.hire_date],["Probation End",e.probation_end_date],["Current Shift",e.shift],["Basic Salary",money(e.basic_salary)]]}/></section>;
 else if(e&&section==='contact')content=<div className="space-y-5"><section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Contact Details</h3><Details items={[["Mobile",e.phone],["Work Email",e.email],["Personal Email",e.personal_email]]}/></section><section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Address</h3><Details items={[["Current Address",e.address]]}/></section></div>;
 else if(e&&section==='supervisor')content=<section className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b p-6 text-xl font-bold">Reporting Structure</h3><Details items={[["Supervisor",e.manager],["Department",e.department],["Employee Position",e.position]]}/></section>;
 else if(e&&section==='documents')content=data.documents.length?<Table headers={['Document','Type','Issue Date','Expiry Date']} rows={data.documents.map(x=>[x.name,x.type,x.issue_date??'—',x.expiry_date??'—'])}/>:<Empty message="No documents or passports have been uploaded."/>;
 else if(e&&section==='payroll')content=data.payrolls.length?<Table headers={['Period','Basic','Bonus','Deductions','Net Pay','Status']} rows={data.payrolls.map(x=>[x.period,money(x.basic),money(x.bonus),money(x.deductions),money(x.net),x.status])}/>:<Empty message="No payroll records are available."/>;
 else if(e&&section==='performance')content=data.reviews.length?<div className="space-y-4">{data.reviews.map(x=><article key={x.id} className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><div><b>{x.date} Review</b><p className="mt-1 text-sm text-slate-500">Reviewed by {x.reviewer}</p></div><span className="flex items-center gap-2 font-bold text-amber-600"><Star className="h-4 w-4"/>{x.score??'—'}/5</span></div><p className="mt-4 text-slate-600">{x.comments||'No comments provided.'}</p></article>)}</div>:<Empty message="No performance reviews are available."/>;
 const Icon=section==='bank'||section==='payroll'?CreditCard:section==='family'?Users:section==='education'?GraduationCap:section==='employment'?Briefcase:section==='contact'?Phone:section==='documents'?FileText:section==='performance'?Star:section==='supervisor'?Users:UserRound;
 return <div className="mx-auto max-w-6xl space-y-7"><button onClick={()=>onNavigate('profile')} className="flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>Employee Profile</button><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="h-6 w-6"/></span><div><h2 className="text-3xl font-bold">{title}</h2><p className="mt-1 text-slate-500">{e?.name??data.account.name}</p></div></div>{content}</div>;
}
function Table({headers,rows}:{headers:string[];rows:Array<Array<string|number>>}){return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map(x=><th key={x} className="px-6 py-4">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t">{row.map((value,i)=><td key={i} className="px-6 py-4 capitalize">{value}</td>)}</tr>)}</tbody></table></div>}
