import { useEffect, useMemo, useState } from 'react';
import { Building2, CalendarDays, Download, FileText, Landmark, PieChart as PieIcon, Search, TrendingUp, WalletCards } from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { Department, getDepartments, getReport, ReportKind } from '../lib/api';

type PayrollRow={employee_id:number;employee_name:string;employee_code:string;department:string|null;basic:number;allowances:number;deductions:number;net:number;status:string;bank_name?:string|null;bank_account?:string|null};
type AttendanceRow={employee_id:number;employee_name:string;employee_code:string;working_days:number;present:number;absent:number;late:number;leave:number};
type CtcRow={employee_id:number;employee_name:string;basic:number;allowances:number;bonus:number;total:number};
type ComponentRow={name:string;amount:number;percentage:number};
type ReportData={rows?:Array<PayrollRow|AttendanceRow|CtcRow|Record<string,unknown>>;totals?:{gross:number;allowances:number;deductions:number};departments?:Array<{name:string;amount:number}>;components?:ComponentRow[];rules?:Array<{name:string;description:string|null;calculation_type:string;value:number}>};

const tabs:Array<{kind:ReportKind;label:string;icon:typeof FileText}>=[
  {kind:'monthly-salary',label:'Monthly Salary',icon:WalletCards},{kind:'salary-summary',label:'Salary Summary',icon:FileText},
  {kind:'bank-advice',label:'Bank Advice',icon:Landmark},{kind:'payslip',label:'Payslip',icon:FileText},
  {kind:'attendance',label:'Attendance',icon:CalendarDays},{kind:'yearly-ctc',label:'Yearly CTC',icon:TrendingUp},
  {kind:'components',label:'Components',icon:PieIcon},
];
const colors=['#4f46e5','#10b981','#f43f5e','#f59e0b','#0ea5e9','#8b5cf6'];
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);
const initials=(name:string)=>name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const mask=(value:unknown)=>{const text=String(value||'');return text?`**** ${text.slice(-4)}`:'Not provided';};

function Empty(){return <div className="flex min-h-64 flex-col items-center justify-center text-center text-slate-500"><FileText className="mb-4 h-10 w-10 text-slate-300"/><p className="font-bold text-slate-700">No report records found</p><p className="mt-1 text-sm">Try another month, department, or employee.</p></div>}
function Avatar({name}:{name:string}){return <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-indigo-50 text-xs font-bold text-indigo-600">{initials(name)}</span>}
function Table({headers,rows}:{headers:string[];rows:Array<Array<React.ReactNode>>}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t">{row.map((cell,i)=><td key={i} className="px-5 py-4">{cell}</td>)}</tr>)}</tbody></table></div>}

export default function ReportsPage(){
  const[kind,setKind]=useState<ReportKind>('monthly-salary');const[month,setMonth]=useState(new Date().toISOString().slice(0,7));
  const[search,setSearch]=useState('');const[departmentId,setDepartmentId]=useState('');const[departments,setDepartments]=useState<Department[]>([]);
  const[data,setData]=useState<ReportData>({});const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{getDepartments().then(setDepartments).catch(()=>undefined);},[]);
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);setError('');getReport<ReportData>(kind,{month,search,department_id:departmentId?Number(departmentId):undefined}).then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to generate report.')).finally(()=>setLoading(false));},250);return()=>clearTimeout(timer);},[kind,month,search,departmentId]);
  const exportRows=useMemo(()=>{if(data.rows?.length)return data.rows; if(data.departments?.length)return data.departments;if(data.components?.length)return data.components;return[];},[data]);
  const exportCsv=()=>{if(!exportRows.length)return;const records=exportRows as Array<Record<string,unknown>>;const keys=Object.keys(records[0]);const quote=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[keys.join(','),...records.map(row=>keys.map(key=>quote(row[key])).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`${kind}-${month}.csv`;link.click();URL.revokeObjectURL(link.href);};
  const content=()=>{if(loading)return <div className="p-20 text-center text-slate-500">Generating report...</div>;if(error)return <div className="rounded-xl bg-red-50 p-6 text-red-700">{error}</div>;
    if(kind==='salary-summary'){const items=data.departments??[];const max=Math.max(...items.map(x=>x.amount),1);if(!items.length)return <Empty/>;return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-3">{[['Total Gross Salary',data.totals?.gross??0,'bg-indigo-600 text-white'],['Total Allowances',data.totals?.allowances??0,'bg-white'],['Total Deductions',data.totals?.deductions??0,'bg-white']].map(([label,value,style])=><div key={String(label)} className={`rounded-xl border p-6 ${style}`}><p className="text-xs font-bold uppercase opacity-70">{label}</p><p className="mt-2 text-3xl font-bold">{money(Number(value))}</p></div>)}</div><section className="rounded-xl border bg-white p-6"><h3 className="font-bold">Departmental Cost Breakdown</h3><div className="mt-6 grid gap-6 md:grid-cols-2">{items.map(x=><div key={x.name}><div className="mb-2 flex justify-between font-semibold"><span>{x.name}</span><span>{money(x.amount)}</span></div><div className="h-2 rounded bg-slate-100"><div className="h-full rounded bg-indigo-500" style={{width:`${x.amount/max*100}%`}}/></div></div>)}</div></section></div>}
    if(kind==='components'){const items=data.components??[];if(!items.length)return <Empty/>;return <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-white p-6"><h3 className="text-center font-bold uppercase">Salary Components Distribution</h3><div className="h-64"><ResponsiveContainer><PieChart><Pie data={items} dataKey="amount" nameKey="name" innerRadius={55} outerRadius={90}>{items.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:number)=>money(v)}/></PieChart></ResponsiveContainer></div>{items.map((x,i)=><div key={x.name} className="mt-3 flex items-center justify-between text-sm"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full" style={{background:colors[i%colors.length]}}/>{x.name}</span><b>{x.percentage}%</b></div>)}</section><section className="rounded-xl border bg-white p-6"><h3 className="font-bold">Component Rules Summary</h3><div className="mt-4 space-y-4">{(data.rules??[]).map(x=><div key={x.name} className="rounded-xl bg-slate-50 p-4"><b>{x.name}</b><p className="mt-1 text-sm text-slate-500">{x.description||`${x.calculation_type} component valued at ${x.value}.`}</p></div>)}</div></section></div>}
    if(kind==='yearly-ctc'){const rows=(data.rows??[]) as CtcRow[];if(!rows.length)return <Empty/>;return <div className="grid gap-5 md:grid-cols-2">{rows.map(x=><article key={x.employee_id} className="rounded-xl border bg-white p-6"><div className="flex items-start justify-between"><div className="flex gap-3"><Avatar name={x.employee_name}/><div><b>{x.employee_name}</b><p className="text-xs uppercase text-slate-500">Annual compensation package</p></div></div><div className="text-right"><p className="text-xs uppercase text-slate-400">Total yearly CTC</p><b className="text-xl text-indigo-600">{money(x.total)}</b></div></div>{[['Annual Basic',x.basic],['Annual Allowances',x.allowances],['Bonus & Incentives',x.bonus]].map(([label,value])=><div key={String(label)} className="mt-4"><div className="flex justify-between text-sm"><span>{label}</span><b>{money(Number(value))}</b></div><div className="mt-2 h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-indigo-500" style={{width:`${x.total?Number(value)/x.total*100:0}%`}}/></div></div>)}</article>)}</div>}
    if(kind==='attendance'){const rows=(data.rows??[]) as AttendanceRow[];if(!rows.length)return <Empty/>;return <Table headers={['Employee','Working Days','Present','Absent','Late','Leave']} rows={rows.map(x=>[<div className="flex items-center gap-3"><Avatar name={x.employee_name}/><div><b>{x.employee_name}</b><p className="text-xs text-slate-400">{x.employee_code}</p></div></div>,x.working_days,<b className="text-emerald-600">{x.present}</b>,<b className="text-rose-600">{x.absent}</b>,<b className="text-amber-600">{x.late}</b>,<b className="text-indigo-600">{x.leave}</b>])}/>}
    if(kind==='bank-advice'){const rows=(data.rows??[]) as Array<Record<string,unknown>>;if(!rows.length)return <Empty/>;return <Table headers={['Beneficiary Name','Account Number','Bank Name','Amount']} rows={rows.map(x=>[<b>{String(x.employee_name)}</b>,<span className="font-mono">{mask(x.account_number)}</span>,String(x.bank_name||'Not provided'),<b>{money(Number(x.amount))}</b>])}/>}
    const rows=(data.rows??[]) as PayrollRow[];if(!rows.length)return <Empty/>;
    if(kind==='payslip')return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><article key={x.employee_id} className="rounded-xl border bg-white p-6"><div className="flex items-center justify-between"><FileText className="h-8 w-8 text-slate-500"/><Download className="h-4 w-4 text-slate-400"/></div><h3 className="mt-5 font-bold">{x.employee_name}</h3><p className="text-sm text-slate-500">{x.employee_code} · {x.department||'Unassigned'}</p><div className="mt-5 border-t pt-4"><p className="text-xs uppercase text-slate-400">Net payable</p><div className="flex justify-between"><b className="text-xl">{money(x.net)}</b><span className="text-sm font-bold text-indigo-600">View Details</span></div></div></article>)}</div>;
    return <Table headers={['Employee','Basic','Allowances','Deductions','Net Salary','Status']} rows={rows.map(x=>[<div className="flex items-center gap-3"><Avatar name={x.employee_name}/><div><b>{x.employee_name}</b><p className="text-xs text-slate-400">{x.employee_code}</p></div></div>,money(x.basic),<span className="text-emerald-600">+ {money(x.allowances)}</span>,<span className="text-rose-600">- {money(x.deductions)}</span>,<b>{money(x.net)}</b>,<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-700">{x.status}</span>])}/>;
  };
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex items-start justify-between"><div><h2 className="text-3xl font-bold">Reports & Analytics</h2><p className="mt-1 text-slate-500">Generate and export comprehensive organizational reports.</p></div><div className="flex rounded-xl border bg-white p-1 text-sm font-bold"><button className="rounded-lg bg-indigo-50 px-4 py-2 text-indigo-600">Standard</button><button className="px-4 py-2 text-slate-500" title="Custom report builder is not configured">Custom</button></div></header><nav className="flex overflow-x-auto rounded-xl bg-slate-100 p-1">{tabs.map(({kind:value,label,icon:Icon})=><button key={value} onClick={()=>setKind(value)} className={`flex min-w-max flex-1 items-center justify-center gap-2 rounded-lg px-4 py-3 text-sm font-bold ${kind===value?'bg-white text-indigo-600 shadow-sm':'text-slate-500'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav><section className="grid gap-4 rounded-xl border bg-white p-5 lg:grid-cols-[1fr_190px_190px_auto]"><label className="flex h-11 items-center gap-3 rounded-xl bg-slate-50 px-4"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or ID..." className="w-full bg-transparent outline-none"/></label><label className="flex h-11 items-center gap-2 rounded-xl bg-slate-50 px-3"><CalendarDays className="h-4 w-4 text-slate-400"/><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="w-full bg-transparent outline-none"/></label><label className="flex h-11 items-center gap-2 rounded-xl bg-slate-50 px-3"><Building2 className="h-4 w-4 text-slate-400"/><select value={departmentId} onChange={e=>setDepartmentId(e.target.value)} className="w-full bg-transparent outline-none"><option value="">All Departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button disabled={!exportRows.length} onClick={exportCsv} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 font-bold text-white disabled:bg-slate-300"><Download className="h-4 w-4"/>Export</button></section>{content()}</div>;
}
